# Generated by Django 5.2.13 on 2026-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorama',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
