# Generated by Django 5.2.13 on 2026-04-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorama',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
